version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-bench
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=qweQWE123!
    ports:
      - "1433:1433"
    restart: unless-stopped
